In [3]:
from scipy import constants
import scipy

print(constants.liter)
print(scipy.__version__)

0.001
1.7.1


In [4]:
# Finding constant pi and other constants
print(constants.pi)
print(dir(constants))

3.141592653589793
['Avogadro', 'Boltzmann', 'Btu', 'Btu_IT', 'Btu_th', 'ConstantWarning', 'G', 'Julian_year', 'N_A', 'Planck', 'R', 'Rydberg', 'Stefan_Boltzmann', 'Wien', '__all__', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '_obsolete_constants', 'acre', 'alpha', 'angstrom', 'arcmin', 'arcminute', 'arcsec', 'arcsecond', 'astronomical_unit', 'atm', 'atmosphere', 'atomic_mass', 'atto', 'au', 'bar', 'barrel', 'bbl', 'blob', 'c', 'calorie', 'calorie_IT', 'calorie_th', 'carat', 'centi', 'codata', 'constants', 'convert_temperature', 'day', 'deci', 'degree', 'degree_Fahrenheit', 'deka', 'dyn', 'dyne', 'e', 'eV', 'electron_mass', 'electron_volt', 'elementary_charge', 'epsilon_0', 'erg', 'exa', 'exbi', 'femto', 'fermi', 'find', 'fine_structure', 'fluid_ounce', 'fluid_ounce_US', 'fluid_ounce_imp', 'foot', 'g', 'gallon', 'gallon_US', 'gallon_imp', 'gas_constant', 'gibi', 'giga', 'golden', 'golden_ratio', 'grain', 'gram', 

In [6]:
# Just binary constants
from scipy import constants

print(constants.kibi)  
print(constants.mebi)   
print(constants.gibi)  
print(constants.tebi)    
print(constants.pebi)   
print(constants.exbi)    
print(constants.zebi)    
print(constants.yobi)    

1024
1048576
1073741824
1099511627776
1125899906842624
1152921504606846976
1180591620717411303424
1208925819614629174706176


In [8]:
from scipy.optimize import root
from math import cos

def eqn(x):
    return cos(x)+x

# here we are finding the value of x given the eqn(x)=0
myroot = root(eqn,0)
print(myroot)

    fjac: array([[-1.]])
     fun: array([0.])
 message: 'The solution converged.'
    nfev: 9
     qtf: array([-2.66786593e-13])
       r: array([-1.67361202])
  status: 1
 success: True
       x: array([-0.73908513])


In [11]:
# In the same way we can also find a minima of a function
from scipy.optimize import minimize

def eqn(x):
    return x**2 + x + 2

# Here 0 acts as the initial guess for root.
mini = minimize(eqn,0,method='BFGS')

print(mini)

      fun: 1.75
 hess_inv: array([[0.50000001]])
      jac: array([0.])
  message: 'Optimization terminated successfully.'
     nfev: 8
      nit: 2
     njev: 4
   status: 0
  success: True
        x: array([-0.50000001])


In [18]:
# scipy is also used to handle sparse values
from scipy.sparse import csr_matrix
import numpy as np

arr = np.array([[0,0,0],[0,1,0],[0,1,0],[2,0,0]])
                
print(csr_matrix(arr))
print(csr_matrix(arr).data)
print(" ")
print(csr_matrix(arr).count_nonzero())

  (1, 1)	1
  (2, 1)	1
  (3, 0)	2
[1 1 2]
 
3


In [19]:
# Here we removed the zeros from matrix and now we only store the data
mat = csr_matrix(arr)
mat.eliminate_zeros()
print(mat)

  (1, 1)	1
  (2, 1)	1
  (3, 0)	2


In [20]:
#Converting the compressed sparse row configuration to a compressed spare column configuration
newmat = mat.tocsc()
print(newmat)

  (3, 0)	2
  (1, 1)	1
  (2, 1)	1


In [25]:
print(newmat.sum_duplicates())
print(mat.sum_duplicates())

None
None


In [26]:
# We can also work with graphs when we are working with scipy as well as it multiple algorithms

from scipy.sparse.csgraph import connected_components

arr = np.array([
    [0,1,2],
    [1,0,0],
    [2,0,0]
])

adj_mat = csr_matrix(arr)
print(connected_components(arr))

(1, array([0, 0, 0], dtype=int32))


In [28]:
from scipy.sparse.csgraph import dijkstra
from scipy.sparse.csgraph import floyd_warshall

print("Dijstra's output")
print(dijkstra(arr, return_predecessors=True, indices=0))
print("Floyd Warshall output")
print(floyd_warshall(arr,return_predecessors=True))

Dijstra's output
(array([0., 1., 2.]), array([-9999,     0,     0], dtype=int32))
Floyd Warshall output
(array([[0., 1., 2.],
       [1., 0., 3.],
       [2., 3., 0.]]), array([[-9999,     0,     0],
       [    1, -9999,     0],
       [    2,     0, -9999]], dtype=int32))
