# Simple Array Operations

In [1]:
import numpy as np
arr = np.array([1,2,3,4,5])
print(arr)
print(type(arr))
np.__version__

[1 2 3 4 5]
<class 'numpy.ndarray'>


'1.23.4'

In [2]:
print(arr.ndim)
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr.ndim

1


3

In [3]:
#Negative indexing
print(arr[-1,1,2])

12


### Slicing in python means taking elements from one given index to another given index.

### We pass slice instead of index like this: [start:end].

### We can also define the step, like this: [start:end:step].

In [5]:
arr[1:]

array([[[ 7,  8,  9],
        [10, 11, 12]]])

In [6]:
## Here we take into consideration all the rows upto but not including 1
arr[:1]

array([[[1, 2, 3],
        [4, 5, 6]]])

In [7]:
### Negative indexing is from behind arr[:-1] remove the last row.
### arr[-1:] is take only the last row as it started from last but one position to last position
print(arr[:-1])
print(arr[-1:])

[[[1 2 3]
  [4 5 6]]]
[[[ 7  8  9]
  [10 11 12]]]


In [8]:
arr[1, 0:,-1:]

array([[ 9],
       [12]])

In [9]:
#How can we change the data type of an array using astype() function
arr = np.array([1.1, 2.1, 3.1])
newarr = arr.astype('i')
print(newarr)
print(newarr.dtype)

[1 2 3]
int32


In [11]:
# Using copy and view for an array
arr = np.array([1,2,3,4,5])

carr = arr.copy()
varr = arr.view()

arr[0] = 42

# Printing the copy
print(carr)
# Changing the original element will have effect on view array
print(varr)

#Printing base of copy will be None but for view it will point to the original array
print(carr.base)
print(varr.base)

[1 2 3 4 5]
[42  2  3  4  5]
None
[42  2  3  4  5]


In [12]:
arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('shape of array :', arr.shape) 

arr = np.array([1,2,4,3,5])
print(arr.shape)

[[[[[1 2 3 4]]]]]
shape of array : (1, 1, 1, 1, 4)
(5,)


In [13]:
#Using numpy reshape command
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
print("Org shape",arr.shape)

arr = arr.reshape(2,3,2)
print("New array",arr)
print("New shape",arr.shape)

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
print(arr.reshape(2, 6).base)
arr = arr.reshape(2,3,2)

arr1 = arr.reshape(-1)
print(arr1)

Org shape (12,)
New array [[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
New shape (2, 3, 2)
[ 1  2  3  4  5  6  7  8  9 10 11 12]
[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [14]:
#Iterating in numpy
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for x in arr:
    for y in x:
        for z in y:
            print(z)

# Instead use np.nditer()
for x in np.nditer(arr):
    print(x)

1
2
3
4
5
6
7
8
1
2
3
4
5
6
7
8


In [15]:
#Ndenumerate where we need the index as well
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for idx, x in np.ndenumerate(arr):
  print(idx, x) 

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8


In [16]:
# In concatinate if the axis is not mentioned it is taken as zero
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2))
print(arr)
arr_a1 = np.concatenate((arr1,arr2), axis=1)
print(arr_a1)

#Now we use stack instead of concatenate
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

arr = np.stack((arr1,arr2))
print(arr)

arr = np.stack((arr1,arr2),axis=1)
print(arr)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
[[[1 2]
  [5 6]]

 [[3 4]
  [7 8]]]
